POST http://localhost:3333/music/create
Content-Type: application/json
Authorization: yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiY2FyZ28iOiJBUlRJU1RBIiwiaWF0IjoxNzAxMzcyMzg4LCJleHAiOjE3MDE0MDExODh9.E0oI3AzTIfr58fzroAPHmrCPvp5b4SLiQNhMIXlIEec

{
    "userId": 1,
    "nome": "Lança Perfume",
    "artista": "Rita Lee",
    "url": "https://test.samedev.repl.co/l3342f3343243_23.mp3",
    "duracao": "5:10",
    "tags": [1, 2],
    "imageUrl": "https://images.genius.com/c59245dcb9e8dff3bfa6e5f47c6703bb.600x600x1.jpg",
    "artistaId": [1]
}

###
POST http://localhost:3333/tags/create
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiY2FyZ28iOiJBRE1JTiIsImlhdCI6MTcwMjE2NzE5MSwiZXhwIjoxNzAyMTk1OTkxfQ._c6ZogiGL8aer1dbX8bc3zUQw2z7WH6ajhKcHVqT_lw
Content-Type: application/json

{
    "nome": "Pop"
}


###
GET http://localhost:3333/tags
Content-Type: application/json

###
DELETE http://localhost:3333/tags/delete/2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiY2FyZ28iOiJBRE1JTiIsImlhdCI6MTcwMjE2NzE5MSwiZXhwIjoxNzAyMTk1OTkxfQ._c6ZogiGL8aer1dbX8bc3zUQw2z7WH6ajhKcHVqT_lw

###
POST http://localhost:3333/music/update/22
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiY2FyZ28iOiJBUlRJU1RBIiwiaWF0IjoxNjk5MDMwNTI0LCJleHAiOjE2OTkwNTkzMjR9.1sk5T6am5R3pShrQPj3Nmy2D2IuJFphcJ7HzDGdWHj8

{
    "userId": 1,
    "nome": "Lança Perfume",
    "artista": "Rita Lee",
    "url": "https://test.samedev.repl.co/l3342f3343243_23.mp3",
    "imageUrl": "https://images.genius.com/c59245dcb9e8dff3bfa6e5f47c6703bb.600x600x1.jpg",
    "artistaId": [1]
}

### 
GET http://localhost:3333/music
Content-Type: application/json


###
POST http://localhost:3333/playlist/add/song/2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiY2FyZ28iOiJBUlRJU1RBIiwiaWF0IjoxNzAyMDY2NjY5LCJleHAiOjE3MDIwOTU0Njl9.UVIH25umQEyVY5JwiZpFv8alx5aNQAtfHFYAecHnJMs

{
    "musicas": [16]
}

###
DELETE http://localhost:3333/playlist/delete/song/2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiY2FyZ28iOiJBUlRJU1RBIiwiaWF0IjoxNzAyMDY2NjY5LCJleHAiOjE3MDIwOTU0Njl9.UVIH25umQEyVY5JwiZpFv8alx5aNQAtfHFYAecHnJMs

{
    "musicas": [16]
}

###
DELETE http://localhost:3333/playlist/delete/2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiY2FyZ28iOiJBUlRJU1RBIiwiaWF0IjoxNzAyMDY2NjY5LCJleHAiOjE3MDIwOTU0Njl9.UVIH25umQEyVY5JwiZpFv8alx5aNQAtfHFYAecHnJMs

###
GET http://localhost:3333/playlist?search=sdds
Content-Type: application/json

###
POST http://localhost:3333/playlist/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiY2FyZ28iOiJBRE1JTiIsImlhdCI6MTcwMjMxMjgyOSwiZXhwIjoxNzAyMzQxNjI5fQ.3H9YFHnwKgVVaHNQ_GGXWFXxhzWf9a7mXSdiS8MKDCA

{
    "nome": "RITA LEE GLOBAL",
    "descricao": "vou pirar",
    "foto": "https://images.genius.com/c59245dcb9e8dff3bfa6e5f47c6703bb.600x600x1.jpg",
    "data": "2023-11-03T16:55:36.350Z",
    "userId": 1,
    "tags": [1]
}

###
DELETE http://localhost:3333/music/delete/21
Content-Type: application/json
Authorization: 
###
POST http://localhost:3333/user/add/like/2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiY2FyZ28iOiJBRE1JTiIsImlhdCI6MTcwMjMyNTIwOCwiZXhwIjoxNzAyMzU0MDA4fQ.KxIu5AqsI2jkPQB2ooOq44qgSvx2XBQPzWSEC4YD_o0

{
    "musicas": [17]
}

### 
POST http://localhost:3333/user/login
Content-Type: application/json

{
    "email": "conradtsamuel@gmail.com",
    "senha": "1234567"
}

### 
POST http://localhost:3333/user/register
Content-Type: application/json

{
    "nome": "Alisson",
    "email": "alissongslaoqslaoq@gmail.com",
    "senha": "1234567",
    "data_nasc": "2006-11-16T00:00:00.000Z"
}

### 
POST http://localhost:3333/user/update/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiY2FyZ28iOiJBUlRJU1RBIiwiaWF0IjoxNjk5OTEyMzc5LCJleHAiOjE2OTk5NDExNzl9.sv8uzhsbtGJHwAivanfMCUbajGrg4EZVRXmoTZelMgE

{
    "nome": "Samuel Conradt",
    "email": "conradtsamuel@gmail.com",
    "cargo": "ADMIN",
    "data_nasc": "2006-12-16T00:00:00.000Z"
}