POST http://localhost:3333/user/
Content-Type: application/json

{
    "nome": "Samuel",
    "email": "asdads@fdfdf.com",
    "post": "Primeiro Post"
}
### 
GET http://localhost:3333/
Content-Type: application/json

###
GET http://localhost:3333/user/123
